# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RestaurantGUI(1).ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import Restuarnt
import simpy
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure

y = [i + 1 for i in range(30)]
def startSimulation():
    Restuarnt.profit = 0
    Restuarnt.averageProfit = 0
    Restuarnt.NUMBER_OF_MONTHS = int(ui.simTime.text())
    Restuarnt.NUM_OF_SIM = int(ui.simNum.text())
    Restuarnt.Arrive = [[0] * 30] * (Restuarnt.NUMBER_OF_MONTHS)
    Restuarnt.waiterCapacity = int(ui.waitersNum.text())
    Restuarnt.cookerCapacity = int(ui.cookersNum.text())
    Restuarnt.waiterSalary = int(ui.waiterSalary.text())
    Restuarnt.cookerSalary = int(ui.cookerSalary.text())
    Restuarnt.TIME_OF_SIM = Restuarnt.NUMBER_OF_MONTHS * 30 * 24 * 60
    for i in range(Restuarnt.NUM_OF_SIM):
        env = simpy.Environment()
        x = Restuarnt.Restaurant(env)
        x.startSimu()

    Restuarnt.sumOfCustomersPerDay()
    
    Restuarnt.netProfit()
    print(Restuarnt.profit / Restuarnt.NUM_OF_SIM)
    ui.resultLabel.setText(str(Restuarnt.profit / Restuarnt.NUM_OF_SIM))
    global y
    y = Restuarnt.ArriveSum
    ui.viewChart(y)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.inputsBox.setGeometry(QtCore.QRect(40, 20, 651, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputsBox.setFont(font)
        self.inputsBox.setObjectName("inputsBox")
        self.simTime = QtWidgets.QLineEdit(self.inputsBox)
        self.simTime.setGeometry(QtCore.QRect(110, 30, 113, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.simTime.setFont(font)
        self.simTime.setText("")
        self.simTime.setObjectName("simTime")
        self.label = QtWidgets.QLabel(self.inputsBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.inputsBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.simNum = QtWidgets.QLineEdit(self.inputsBox)
        self.simNum.setGeometry(QtCore.QRect(110, 50, 113, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.simNum.setFont(font)
        self.simNum.setText("")
        self.simNum.setObjectName("simNum")
        self.label_3 = QtWidgets.QLabel(self.inputsBox)
        self.label_3.setGeometry(QtCore.QRect(300, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.inputsBox)
        self.label_4.setGeometry(QtCore.QRect(300, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.waiterSalary = QtWidgets.QLineEdit(self.inputsBox)
        self.waiterSalary.setGeometry(QtCore.QRect(390, 30, 113, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.waiterSalary.setFont(font)
        self.waiterSalary.setText("")
        self.waiterSalary.setObjectName("waiterSalary")
        self.cookerSalary = QtWidgets.QLineEdit(self.inputsBox)
        self.cookerSalary.setGeometry(QtCore.QRect(390, 50, 113, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cookerSalary.setFont(font)
        self.cookerSalary.setText("")
        self.cookerSalary.setObjectName("cookerSalary")
        self.label_5 = QtWidgets.QLabel(self.inputsBox)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.waitersNum = QtWidgets.QLineEdit(self.inputsBox)
        self.waitersNum.setGeometry(QtCore.QRect(110, 70, 113, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.waitersNum.setFont(font)
        self.waitersNum.setText("")
        self.waitersNum.setObjectName("waitersNum")
        self.cookersNum = QtWidgets.QLineEdit(self.inputsBox)
        self.cookersNum.setGeometry(QtCore.QRect(390, 70, 113, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cookersNum.setFont(font)
        self.cookersNum.setText("")
        self.cookersNum.setObjectName("cookersNum")
        self.label_6 = QtWidgets.QLabel(self.inputsBox)
        self.label_6.setGeometry(QtCore.QRect(300, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(470, 150, 121, 23))
        self.runButton.setObjectName("runButton")
        self.runButton.clicked.connect(startSimulation)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 150, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.outputsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.outputsBox.setGeometry(QtCore.QRect(40, 190, 651, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputsBox.setFont(font)
        self.outputsBox.setObjectName("outputsBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(666, 510, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.averageLabel = QtWidgets.QLabel(self.outputsBox)
        self.averageLabel.setGeometry(QtCore.QRect(10, 30, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.averageLabel.setFont(font)
        self.averageLabel.setObjectName("averageLabel")
        self.averageLabel.setText("Profit: ")
        
        self.resultLabel = QtWidgets.QLabel(self.outputsBox)
        self.resultLabel.setGeometry(QtCore.QRect(65, 30, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-3, 500, 751, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(570, 510, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.status.setFont(font)
        self.status.setObjectName("status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.simTime.setText(str(Restuarnt.NUMBER_OF_MONTHS))
        self.cookerSalary.setText(str(Restuarnt.cookerSalary))
        self.waiterSalary.setText(str(Restuarnt.waiterSalary))
        self.waitersNum.setText(str(Restuarnt.waiterCapacity))
        self.cookersNum.setText(str(Restuarnt.cookerCapacity))
        self.simNum.setText(str(Restuarnt.NUM_OF_SIM))
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Restaurant Simulation"))
        self.inputsBox.setTitle(_translate("MainWindow", "Inputs"))
        self.label.setText(_translate("MainWindow", "Simulation Time:"))
        self.label_2.setText(_translate("MainWindow", "#of Simulations:"))
        self.label_3.setText(_translate("MainWindow", "Waiter Salary:"))
        self.label_4.setText(_translate("MainWindow", "Cooker Salary:"))
        self.label_5.setText(_translate("MainWindow", "#of Waiters:"))
        self.label_6.setText(_translate("MainWindow", "#of Cookers:"))
        self.runButton.setText(_translate("MainWindow", "Run Simulation"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.outputsBox.setTitle(_translate("MainWindow", "Outputs"))
        self.label_7.setText(_translate("MainWindow", "Status"))
        self.status.setText(_translate("MainWindow", "idle"))

    def viewChart(self, data):
        plt.plot(data)
        plt.xlabel("days")
        plt.ylabel("# of customers")
        plt.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
